export const CHANGE_USERNAME = "@TEASIM_BOILERPLATE/CHANGE_USERNAME";

export const LOAD_REPOS = "@TEASIM_BOILERPLATE/LOAD_REPOS";
export const LOAD_REPOS_SUCCESS = "@TEASIM_BOILERPLATE/LOAD_REPOS_SUCCESS";
export const LOAD_REPOS_ERROR = "@TEASIM_BOILERPLATE/LOAD_REPOS_ERROR";
